A-Game-of-Search/zombie-game/zombie_project/zombieGame/urls.py
from django.conf.urls import patterns, url
from zombieGame import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        # url(r'^login/$', views.login, name='login'),
        url(r'^profile/$', views.profile, name='profile'),
        url(r'^game/$', views.game, name='game'),
        url(r'^leaderboard/$', views.leaderboard, name='leaderboard'),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name = 'logout'),
        #url(r'^game/WAIT/$', views.wait, name= 'wait'),
        #url(r'^game/house/$', views.house, name= 'house'),
        url(r'^turn/(?P<turn_options_slug>[\w\-]+)/$', views.turn, name='turn'),
)
#(?P<turn_name_slug>[\w\-]+)/

A-Game-of-Search/zombie-game/zombie_project/zombie_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'zombie_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^zombieGame/', include('zombieGame.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

A-Game-of-Search/zombie-game/zombie_project/zombieGame/models.py
from django.db import models
from django.contrib.auth.models import User
# do we put badges in here ??? :S
# TRYING TO SLUG ACTIONS. MAYBE NEED TO MAKE A VIEW FOR THEM

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    # Stats and badges
    kills = models.IntegerField(default = 0)
    days = models.IntegerField(default = 1)
    people = models.IntegerField(default = 1)
    food = models.IntegerField(default = 3)
    ammo = models.IntegerField(default = 2)
    time = models.IntegerField(default = 100)
    survivorBadge = models.IntegerField(default = 0)
    killerBadge = models.IntegerField(default = 0)
    staminaBadge = models.IntegerField(default = 0)
    partyBadge = models.IntegerField(default = 0)

    def __unicode__(self):
        return self.user.username

#class Fill_dict(models.Model):
 #   turn = models.CharField(max_length=30)
  #  s = models.SlugField(editable=True)

   # def save(self):
    #    if not self.id:
     #       self.s = slugify(self.options)

      #  super(turn, self).save()

 #   def __unicode__(self):
  #             return self.options


A-Game-of-Search/zombie-game/zombie_project/zombieGame/forms.py
from django import forms
from django.contrib.auth.models import User
from zombieGame.models import UserProfile

#Basic user form, creates a username, email and password forms.
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

#User Profile Form, allows a picture to be uploaded
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

A-Game-of-Search/zombie-game/zombie_project/zombieGame/views.py
import user
from models import UserProfile
from django.shortcuts import render, render_to_response
from forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

from engine.main import show_game_screen
from engine.game import Game

#Homepage view
def index(request):
    return render(request, 'zombieGame/index.html')

#Login view
def login(request):
    context_dict = {'boldmessage': "login"}
    return render(request, 'zombieGame/login.html', context_dict)

#Profile view, requires user to be logged in
@login_required
def profile(request):
    context = RequestContext(request)
    profile = request.user.userprofile
    kills = request.user.userprofile.kills
    days = request.user.userprofile.days
    people = request.user.userprofile.people
    picture = request.user.userprofile.picture
    context_dict = {'profile': profile, 'kills': kills,'days': days, 'people':people, 'picture':picture}
    return render_to_response('zombieGame/profile.html', context_dict, context)
#def start_game(request):

#need to add ammo, partysize, days

#In this view we create a context_dict variable, which we can alter what is outputted to the game.html
def fill_dict(g):

    if g.game_state == 'STREET':
        context_dict = {'street': g.street, 'house_list': g.street.house_list, 'current_house':g.street.get_current_house(), 'turn': g.turn_options(),
                        'house_num': ['house_no']}
        return context_dict

        i=0
        for i in g.street.house_list:
            context_dict['house_no'].append(i)
            i += 1


    elif g.game_state == 'HOUSE':
        context_dict = {'house': g.street.get_current_house(),'room': g.street.get_current_house().get_current_room()}
        return context_dict

    elif g.game_state == 'ZOMBIE':
        context_dict = {'street': g.street, 'house_list': g.street.house_list,
                        'current_house':g.street.get_current_house(),
                        'current_room':g.street.get_current_house().get_current_room(),
                        'zombies': g.street.get_current_house().current_room.zombies}
        return context_dict


def turn(user, turn, value=None):
    if g.take_turn(turn) == 'WAIT':
        return game(request)
    elif g.take_turn(turn) == 'ENTER':
        context_dict = {'user': user }
        return context_dict
    #not working

#The main game view, requires user to be logged in
@login_required
def game(request):
    g = Game()
    g.start_new_day()
    context_dict=fill_dict(g)
    return render(request, 'zombieGame/game.html', context_dict)

#Leaderboards view, requires user to be logged in
@login_required
def leaderboard(request):
     num = [1,2,3,4,5,6,7,8,9,10]
     kills = UserProfile.objects.order_by('-kills')[:10]
     days = UserProfile.objects.order_by('-days')[:10]
     context_dict = {'index':num, 'kills':kills, 'days':days}
     return render(request, 'zombieGame/leaderboard.html', context_dict)

#Register view
def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # profile.user.kills = 0
            # profile.user.survival = 0

            profile.save()

            registered = True

        else:
            print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
            'zombieGame/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )

#Login view
def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect('/zombieGame/profile/')
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'zombieGame/login.html', {})

#Logout view
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/zombieGame/')

A-Game-of-Search/zombie-game/zombie_project/templates/zombieGame/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>

<head>
  <meta charset="utf-8">
  <title>Zombies</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/starter-template/" rel="stylesheet">

</head>

<style>

    img.displayed {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }

    .center {
        margin: auto;
        background-color: white;
        height: 720px;
        width: 1280px;
        border: 10px solid black;
        padding: 10px;
    }

    .white {
        color: white;
    }

    ul {
        list-style-type: none;
        width: 1280px;
        margin: auto;
        padding: 0;
        overflow: hidden;
        background-color: #000;
    }

    li {
        float: left;
    }

    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 20px 25px;
        text-decoration: none;
    }

    li a:hover{
        background-color: #333;
    }

</style>

<!-- Html for the background and header -->

<img class="displayed" src = "{% static "images/ZombieGameBanner.png" %}" alt = "Zombie Banner" />
<body background = "{% static "images/homepage.jpg" %}" align = "middle"/>

<!-- Html for the navigation bar -->

    <ul>
    <li><a href="/zombieGame/game/" >Play!</a></li>
    <li><a href="/zombieGame/profile/" >Profile</a></li>
    <li><a href="/zombieGame/leaderboard/" >Leaderboard</a></li>
    <li><a href="/zombieGame/" >Logout</a></li>
    </ul>

<body>

    <div class="center">
      {% block content %}{% endblock content %}
    </div>
</body>

</html>

A-Game-of-Search/zombie-game/zombie_project/templates/zombieGame/game.html
<!DOCTYPE html>
{% extends "zombieGame/base.html" %}
<html lang="en">

{% load staticfiles %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <title>ZOMBIE</title>

</head>
<body>
   {{ game }}  </br>
       {{street}}
           {% for t in turn %}
                   <p><a href={{t}}>{{t}}</p>
           {% endfor %}
           {% for house in house_list %}
               <p><a href="house"><img src="{% static "images/2house.jpg" %}" alt = "House" /></a></p>
           {% endfor %}
       {{house}}
            {% for room in house %}
                <p><a href="room">{{room}}</a>
            {% endfor %}



</body>

{% endblock content %}

</html>

A-Game-of-Search/zombie-game/zombie_project/templates/zombieGame/index.html
<!DOCTYPE>
{% extends "zombieGame/base.html" %}

{% load static %}

<html>

<head>
    <title>Zombie Home</title>
</head>

{% block content %}

<body>
    <p><font size="10"> Thanks for playing ! Login to play more:</p>
    <a href="/zombieGame/login/">Login Here!</a><br />
    <img src="{% static "images/thriller.jpg" %}" alt="MJ" />
</body>

{% endblock content %}

</html>

A-Game-of-Search/zombie-game/zombie_project/templates/zombieGame/leaderboard.html
<!doctype html>
{% extends "zombieGame/base.html" %}
<html lang="en">
<head>
	<h1 align="center">Leaderboard</h1>
	<h3><a href="/zombieGame/">HomePage</a></h3>
  <meta charset="utf-8">
  <title>Leaderboard</title>

  {% block content %}

  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script>
  $(function() {
    $( "#tabs" ).tabs();
  });
  </script>

</head>
{% block bg %}
{% endblock bg %}
<body>


<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Survivors</a></li>
    <li><a href="#tabs-2">Killers</a></li>
  </ul>
  <div id="tabs-1">
    <p>Most days spend alive!</p>
    <hr>
    {% for each in days  %}
      <p>  {{ each }}  {{ each.days }}</p>
      <hr>

    {% endfor %}
    
  </div>
  <div id="tabs-2">
    <p>Most zombies killed!</p>
    <hr>

    {% for each in kills %}
       <p> {{ each }}  {{ each.kills }}</p>
       <hr>
    {% endfor %}
    
  </div>
</div>


</body>

   {% endblock content %}

</html>

A-Game-of-Search/zombie-game/zombie_project/templates/zombieGame/login.html
<!DOCTYPE html>
{% extends "zombieGame/base.html" %}
<html>
    <head>

        <title>login</title>
    </head>

    {% block content %}

    <body>
        <h1>Login first!</h1>

        <form id="login_form" method="post" action="/zombieGame/login/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" /><br />
            Password: <input type="password" name="password" value="" size="50" /><br />

            <input type="submit" value="submit" />
        </form>
    <p>Don't have an account? Sign up!</p>
    <a href="/zombieGame/register/">Register Here</a><br />
    <!--<a href="/zombieGame">Home</a>-->

    </body>

    {% endblock content %}

</html>

A-Game-of-Search/zombie-game/zombie_project/templates/zombieGame/profile.html
<!DOCTYPE html>
{% extends "zombieGame/base.html" %}

{% load static %}
{% load media %)
<html xmlns="http://www.w3.org/1999/html">

	<head>
		<title>Profiles</title>
	</head>

	{% block content %}

	<H1 style="text-align:center;">Profiles Page</H1>
        <p<b>Welcome back {{ user.username }}!</b></p>

<div class="container">
    <div class="row">
        <div class="col-sm-2 col-md-2">
            <img src="{{ profile.picture.url }}" alt="user profile"  alt height="200", width="200"/>
        </div>
        <div class="col-sm-4 col-md-4">
            <blockquote>
                <p>User name: {{profile}}</p>
            </blockquote>
                <br/> <p><i class="glyphicon glyphicon-fire"></i>Best Kills:{{profile.kills}}
                <br/> <p><i class="glyphicon glyphicon-globe"></i>Survival:{{profile.days}}
                <br/> <p><i class="glyphicon glyphicon-user"></i>Most friends:{{profile.people}}
        </div>
        <div class="col-sm-4 col-md-4 ">
		 <button type="button" class="btn btn-default"><a href = "/zombieGame/logout/">LOGOUT</button>


    </div>
</div>

	</body>

	{% endblock content %}

</html>
<div class="container">
    <div class="row">
        <div class="col-sm-2 col-md-2">
            <img src="{% static "{{profile.picture}}" %}" alt = "Profile Picture"  />
            alt="" class="img-rounded img-responsive" />
        </div>
        <div class="col-sm-4 col-md-4">
            <blockquote>
                <p>User name: {{profile}}</p>
            </blockquote>
            <p> <i class="glyphicon glyphicon-envelope"></i><p>Best Kills: </p>{{profile.kills}
                <br
                /> <i class="glyphicon glyphicon-globe"></i><p>Survival: </p>{{profile.days}}
                <br /> <i class="glyphicon glyphicon-gift"></i><P>Most friends: </P>{{profile.people}}
        </div>
        <div class="col-sm-2 col-md-2">
            <img src="http://thetransformedmale.files.wordpress.com/2011/06/bruce-wayne-armani.jpg"
            alt="" class="img-rounded img-responsive" />
        </div>
		 <a href = "/zombieGame/logout/">Logout</a><br />

    </div>
</div>

A-Game-of-Search/zombie-game/zombie_project/templates/zombieGame/register.html
<!DOCTYPE html>
{% extends "zombieGame/base.html" %}
<html>


    <head>
        <title>Register</title>
    </head>

    {% block content %}

<form role="form"  method="post" action=".">
                {% csrf_token %}

<h2 class="form-signin-heading">Sign Up Here</h2>

<div class="form-group" >
 <p class="required"> <label for="id_username">Username:</label>
     <input class="form-control"  id="id_username" maxlength="30" name="username" type="text"  placeholder="Enter username"/></p>
</div>
 <div class="form-group">
    <p class="required"><label for="id_email">E-mail:</label>
        <input class="form-control" id="id_email" name="email" type="email" placeholder="Enter email" /></p>
 </div>
<div class="form-group">
    <p class="required"><label for="id_password1">Password:</label>
        <input class="form-control" id="id_password1" name="password1" type="password" placeholder="Enter password" /></p>
</div>
<div class="form-group">
    <p class="required"><label for="id_password2">Password (again):</label>
 <input class="form-control" id="id_password2" name="password2" type="password" placeholder="Enter password again" /></p>
</div>
<div class="form-group">
    <p class="required"><label for="id_picture" >Upload a profile picture :</label>
 <input id="id_picture" name="picture" type="file" placeholder="Upload a picture" /></p>
</div>

<button type="submit" class="btn btn-default">Submit</button>

        </form>
{% endblock %}